version: '3'
services:
  front-end:
    container_name: react-client
    build:
      context: ./client
    ports:
      - "3000:80"

  back-end:
    container_name: spring-boot-api
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@database:1521:xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
    depends_on:
      database: 
        condition: service_healthy

  database:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: exit 0
volumes:
  oracle-data:
    driver: local
